filetype on
filetype indent on
syntax on
set nowrap
colorscheme monokai
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
set guifont=Hack\ Regular:h18
set number
set hidden
set history=100
