filetype on
filetype indent on
syntax on
colorscheme monokai-soda
set nowrap
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set smarttab
set autoindent
set number
set hidden
set history=100
